### PR TITLE
New convoy frequency setting

### PR DESCRIPTION
**Pull request by Justin7654**
- Added setting for convoy frequency

_Bugs possible with the timer (unless it uses > or < and not == )_

Maybe next i will add a setting to disable the 1 hour that the supply vehicle takes to despawn, for performance reasons, was going to do it this pull request but it looked really complex

### CODE REVIEW

**Comment by Justin7654** [comment]
Oops forgot to include the built file, I don’t think I can change it now

**Comment by Toast732** [comment]
you can change it still, if you update your fork, it will automatically include the changes in this PR

**Comment by Justin7654** [comment]
just notifying you since this seems to have been buried and forgotten

**Review by Toast732 — APPROVED** [review]
Looks Good.

**Pull request merged**
